### ISSUE TITLE
Styles, scripts, and images are not loaded over HTTPS, when FORCE_SSL_ADMIN is true

### ISSUE THREAD

**Issue by waviaei** [miya0001/wp-total-hacks#35]
When site URL is set in `http://~`, but  admin is forced SSL, i.e.`define( 'FORCE_SSL_ADMIN', true );`, WP Total Hacks tries to load its scripts and styles in over HTTP, rather than HTTPS.

Chrome's developer tool Console displays several errors like this:

> Mixed Content: The page at 'https://www.tuj.ac.jp/news/wp-admin/options-general.php?page=wp-total-hacks' was loaded over HTTPS, but requested an insecure stylesheet 'http://www.tuj.ac.jp/news/wp-content/plugins/wp-total-hacks/css/style.css'. This request has been blocked; the content must be served over HTTPS.

Same error message for: style.css, ui.tabs.css, wp-total-hacks-upload.js, and wp-total-hacks.js, 
Warning message for: check.png

**Comment by miya0001** [comment]
Thanks! I'll fix it on the next release. :)

**Comment by waviaei** [comment]
:+1:

**Comment by waviaei** [comment]
Here, `admin_url()` is used.

https://github.com/miya0001/wp-total-hacks/blob/master/includes/admin.php#L388

And according to the docs, `admin_url()` has a second paramenter which by default should obey WordPress' ssl ... but somehow wp total hacks is not obeying..?

https://developer.wordpress.org/reference/functions/admin_url/

**Comment by miya0001** [comment]
Ah, I forgot to fix this problem ... :)

**Comment by waviaei** [comment]
May be now is the time ... ! :-)

> To run WordPress we recommend your host supports:
PHP version 7 or greater
MySQL version 5.6 or greater OR MariaDB version 10.0 or greater
HTTPS support

https://wordpress.org/about/requirements/

**Comment by miya0001** [comment]
@waviaei 

Please write like following in `wp-config.php`.

```
define( "WP_HOME", "//example.com" );
define( "WP_SITEURL", "//example.com" );
```

**Comment by waviaei** [comment]
@miya0001 
That did not work. It won't even let me to login to Admin. It will just show the login screen again.
But this did.

```
define( "WP_HOME", "https://example.com" );
define( "WP_SITEURL", "https://example.com" );
```

So I did that temporary*, and changed back the setting.
 
*I realized that uploading uses jquery, and that did not work.

**Comment by miya0001** [comment]
OK thanks, but I won't fix it.
Please make your site enforce SSL. 😄

**Comment by waviaei** [comment]
Yeah thats fine 😄
